# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 833a5d788efb7ec08a03f0c4d49d759ee2e9589bdfaaa7054b7d5eab745f0052a4070041e1847a280ace21ba869dc3d30e8909175379cc99f11f21fc36f53ae3

test:
  secret_key_base: 6ffeb105673f17814392790f73a9539744365e8fc7f4aac61414cc3096505aed7c262a932cc5f9eb9eae030c741e43db8ea50c7df9689a1abff237813e67bfd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
